* How to get images?
** Linux[fn:2]

** Windows[fn:1]
    OpenStack Windows Server 2012 R2 Evaluation
    Microsoft Windows Server 2012 R2 Standard Evaluation is now available as a downloadable image that can be directly deployed to OpenStack!

    Supported hypervisors:
      - Hyper-V
      - KVM
      - XenServer / XCP

    All the images come with the required hypervisor specific drivers and tools, for example VirtIO for KVM and XenServer tools for XenServer / XCP.

    Our Cloudbase-Init is also installed and the image has been properly sysprepped and generalized, no additional work is required on your side.

    Deploying Windows OpenStack instances has never been so easy!

    This is an official release and Microsoft provided a specific EULA that needs to be accepted before download. Please note in particular that this is an evaluation edition 
    meant to be used in test environments only.
    
    User access
    This image comes with RDP enabled. Cloudbase-Init creates a user called “Admin” during the instance initialization. Starting with OpenStack Grizzly, the password can be retrieved with:
    #+begin_example
    nova get-password <instance id or name> <path to SSH private key>    
    #+end_example
    
    The usual Windows “Administrator” user is also available, but in order to enable it the password must be changed by accessing the instance console (e.g. from the Horizon dashboard).

    Note: by default in Windows Server 2012 ping requests are blocked by the firewall.

    Glance deployment
    Deploying your downloaded image to Glance is very easy. You can even specify a hypervisor\_type property and support multiple hypervisors with different images, for example:
    #+begin_example
    gunzip -cd  windows_server_2012_r2_standard_eval_hyperv_20131031.vhd.gz | \
    glance image-create --property hypervisor_type=hyperv --name "Windows Server 2012 R2 Std Eval" \
    --container-format bare --disk-format vhd    
    #+end_example


* Footnotes

[fn:1] http://www.cloudbase.it/ws2012r2/

[fn:2] http://docs.openstack.org/image-guide/content/ch_obtaining_images.html
